name: NPM Package

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm t
      - run: npm publish --access public
      - run: npm profile set email contato@alexbruno.dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
